### PR TITLE
Use PyBytes instead of PyString regardless of Python version

### PR DESCRIPTION
**Pull request by sp1ky**
* There's no need to use a conditional since PyBytes exists in
  both Python 2 and 3
* http://cython.readthedocs.io/en/latest/src/tutorial/strings.html
  #python-string-types-in-cython-code
* Also increment version to 0.1.8

### CODE REVIEW

**Comment by sp1ky** [comment]
Thanks for the prompt merge earlier @escherba. Assuming you see fit to also merge this, could you `make release` also? Thanks

**Comment by escherba** [comment]
Hi David,

It publishes to PyPI every time CircleCI build passes (which it didn't at
first because of some issue with "easy_install"). Latest release should be
on PyPI now.

Thanks for the commits.

- Eugene

**Comment by escherba** [comment]
Getting `Symbol not found: _PyInt_Type` when building extension with pip3...

**Comment by sp1ky** [comment]
What version of Python 3 are you using? It works fine for me on Python 2.7 and 3.5.

```
virtualenv env -p python3.5 && source env/bin/activate
pip3 install cityhash
python3 -c "import cityhash; print(cityhash); print(cityhash.CityHash128('test'))"
<module 'cityhash' from '<...>/env/lib/python3.5/site-packages/cityhash.cpython-35m-x86_64-linux-gnu.so'>
22897019227668213506489618725052538632
```

**Comment by sp1ky** [comment]
Also, the Cython output seems to account for this: https://github.com/escherba/python-cityhash/blob/master/src/cityhash.cpp#L282. Are you maybe missing the python3-dev headers?

**Comment by escherba** [comment]
Nevermind, just pushed a release (v0.1.10) that fixes it. Probably had to do with cython-generated code, not with PYX file.

**Comment by sp1ky** [comment]
Ah. I like an easy fix :grinning:

**Pull request merged**
