### PR TITLE
make CithyHash128WithSeed use the seed

### PR DESCRIPTION
**Pull request by Marnixvdb**
While working in Python on a hashing routine that leverages the CityHash128WithSeed function, I noticed the seed is ignored. The proposed code change fixes this. However, when people are using the method with a seed, the previously incorrect output will now be generated with the seed, and thus different than before. This could cause issues for existing users of the library. 

I wanted to contribute tests for this function that would have caught the issue, but I couldn't get that to work on my local machine, probably because I am too unfamiliar with C-based workflows. I wouldn't mind writing them, but would need a pointer on how to do it.

### CODE REVIEW

**Comment by escherba** [comment]
Thank you very much, this looks like a real bug. I am happy to give you help how to set up testing. I will need to spend an hour or two studying this codebase since i haven't looked at it in a long time!

**Comment by Marnixvdb** [comment]
Yeah I saw that the last update was quite a while ago. I tried to add a test to tests/test_cityhash.cc, or to make the current tests fail. Neither had any impact on the result of "make test" or "make", so I must be doing something wrong or missing something. Like I said: I'm unfamiliar with C workflows, so I was already happy that I got the project to compile, and that I was able to test my change from the Python shell. Anyway, agree it's a real bug, so I'm happy to contribute to a resolution.

**Comment by escherba** [comment]
Ok, I ran tests both in automated mode and manually, and here is what I learned: The simple truth is that you do not see the tests fail because there are no tests that test the effect of the seed! Currently adding them.

**Comment by escherba** [comment]
Oh actually I saw you wanted to add tests -- I will let you do that, but meanwhile I will merge my own PR that has a slightly updated workflow.

**Comment by escherba** [comment]
more specifically, if you type `make test` and `make cpp-test`, it should run all the tests that are available.

**Comment by Marnixvdb** [comment]
Thanks Eugene, that helped! I've added additional tests to tests/test_cityhash.cc, for increased cpp-test coverage. I've also added a single test to tests/test_cityhash.py to double-check different outcomes for different seeds. Let me know if you need anything else!

**Comment by escherba** [comment]
LGTM! merging

**Comment by Marnixvdb** [comment]
Many thanks for the quick responses and the support!

**Comment by escherba** [comment]
Thank you for contributing. FYI, I now added FarmHash to this repo as well.

**Pull request merged**
