### PR TITLE
Windows 10, python 3.7, cannot install clickhouse-cityhash

### PR DESCRIPTION
**Pull request by ghuname**
... /Fobuild\temp.win-amd64-3.7\Release\src/city.obj -O3 -msse4.2 -Wno-unused-value -Wno-unused-function
    cl : Command line error D8021 : invalid numeric argument '/Wno-unused-value'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Is there any solution for the problem?

### CODE REVIEW

**Comment by yujiaao** [comment]
pip install cityhash
Collecting cityhash
  Using cached cityhash-0.2.3.post9.tar.gz (48 kB)
Using legacy setup.py install for cityhash, since package 'wheel' is not installed.
Installing collected packages: cityhash
    Running setup.py install for cityhash ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\projects\frontera\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xingwanxiang\\AppData\\Local\\Temp\\pip-install-uojle6le\\cityhash\\setup.py'"'"'; __file__='"'"'C:\\Users
\\xingwanxiang\\AppData\\Local\\Temp\\pip-install-uojle6le\\cityhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"
'"'))' install --record 'C:\Users\xingwanxiang\AppData\Local\Temp\pip-record-ctomkob3\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\projects\frontera\venv\include\site\python3.8\cityhash'
         cwd: C:\Users\xingwanxiang\AppData\Local\Temp\pip-install-uojle6le\cityhash\
    Complete output (11 lines):
    running install
    running build
    running build_ext
    building 'cityhash' extension
    creating build
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iinclude -Id:\projects\frontera\venv\include -IC:\Python38\include -IC:\Python38\incl
ude "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\s
hared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tpsrc/city.cc
/Fobuild\temp.win-amd64-3.8\Release\src/city.obj -O3 -Wno-unused-value -Wno-unused-function
    cl: 命令行 error D8021 :无效的数值参数“/Wno-unused-value”
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\projects\frontera\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xingwanxiang\\AppData\\Local\\Temp\\pip-install-uojle6le\\cityhash\\setup
.py'"'"'; __file__='"'"'C:\\Users\\xingwanxiang\\AppData\\Local\\Temp\\pip-install-uojle6le\\cityhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(co
mpile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\xingwanxiang\AppData\Local\Temp\pip-record-ctomkob3\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\projects\frontera\venv\include\
site\python3.8\cityhash' Check the logs for full command output.

**Comment by yujiaao** [comment]
> cl: 命令行 error D8021 :无效的数值参数“/Wno-unused-value”
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64\cl.exe' failed with exit status 2

I fix this error on Windows by my fork

**Comment by escherba** [comment]
@xzkostyan do you want me to merge this? This includes quite a lot of changes

**Comment by xzkostyan** [comment]
@escherba nope, I definitely don't.

We need downgraded version 1.0.2 CityHash algorithm for ClickHouse. That's why I've done all the cut-off and downgrade stuff in fork and upload package to pypi in different name. This changes should not be merged into upstream.

The solution to redistribute hashing algorithm in different package was caused to pure `clickhouse-driver` python package portability. This was long time ago. Before code cythoninsation and wheels packaging.

@ghuname @yujiaao  feel free to open PRs [in my fork](https://github.com/xzkostyan/python-cityhash) if these changes are ClickHouse-releated.

@escherba there is a note about it in my fork's README:

> A fork of Python wrapper around CityHash with downgraded version of algorithm. This fork used as 3-rd party library for hashing data in ClickHouse protocol. Unfortunately ClickHouse server comes with built-in old version of this algorithm.
> 
> Please use original python-cityhash package for other purposes.

Maybe we should somehow to rephrase this part for not bothering you in the future?

**Comment by escherba** [comment]
@xzkostyan Thanks for the detailed reply. It could help if you renamed your fork to "clickhouse-cityhash" to reduce the confusion (unless you have some strong reason not to, of course).

**Comment by escherba** [comment]
Closing this PR as build on Windows are now supported (verified via GitHub actions).

**Comment by xzkostyan** [comment]
I've renamed my fork to "clickhouse-cityhash".

**Pull request closed without merging**
